- name: Install Core Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install metaapi-cloud-sdk pandas
          # Instalaci√≥n forzada desde la fuente oficial
          pip install git+https://github.com/twopirllc/pandas-ta.git@development
